### ISSUE TITLE
世界上最好玩的游戏是什么

### ISSUE THREAD

**Issue by bingxueailin** [bingxueailin/discussiondiscussion#2]
### Discussed in https://github.com/bingxueailin/discussiondiscussion/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **bingxueailin** August 21, 2023</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by JUSTINAYA** [comment]
是原神！

**Comment by bingxueailin** [comment]
> 是原神！

你是对的
